---
- name: Install ntp packages
  apt:
    pkg:
    - systemd-timesyncd
    state: latest
  become: yes

- name: Enable ntp synchronization
  ansible.builtin.shell:
    cmd: timedatectl set-ntp true
  become: yes
...
