---
- name: Install longhorn apt requirements
  apt:
    pkg:
    - open-iscsi
    - lvm2
    state: latest

- name: Enable and restart open-iscsi
  ansible.builtin.systemd:
    name: open-iscsi
    state: restarted
    enabled: yes

- name: Load iscsi_tcp module
  shell:
    cmd: modprobe iscsi_tcp

- name: Auto-load iscsi_tcp module on startup
  shell:
    cmd: echo iscsi_tcp > /etc/modules-load.d/iscsi-tcp.conf
...
