---
- name: Install longhorn apt requirements
  apt:
    pkg:
    - open-iscsi
    - lvm2
    state: latest

- name: Install longhorn Ubuntu apt requirements
  apt:
    pkg:
    - linux-modules-extra-raspi
    state: latest
  when: ansible_distribution == "Ubuntu"

# Need restart to use the newly installed kernel modules
- name: Reboot machine
  reboot:
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Enable and restart open-iscsi
  ansible.builtin.systemd:
    name: open-iscsi
    state: restarted
    enabled: yes

- name: Load iscsi_tcp module
  shell:
    cmd: modprobe iscsi_tcp
  become: true

- name: Auto-load iscsi_tcp module on startup
  shell:
    cmd: echo iscsi_tcp > /etc/modules-load.d/iscsi-tcp.conf
...
