---
- name: Disable swapfile
  shell:
    cmd: dphys-swapfile swapoff && dphys-swapfile uninstall
  become: yes

- name: Disable swapfile service
  ansible.builtin.systemd:
    name: dphys-swapfile
    state: stopped
    enabled: no
  become: yes

- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  become: yes
...
